[package]
name = "rasters"
version = "0.1.0"
authors = ["Rajsekar Manokaran <rajsekar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Math and algo deps
num = "0.2.1"
cgmath = {version = "0.17.0", features = ["serde"]}
ndarray = {version = "0.13.0", features = ["serde-1"]}
spade = "1.8.1"

# CLI deps
failure = "0.1.6"
cli = { version = "0.1.0", registry = "aspecscire" }
clap = "2.33.0"

# GIS deps
geo = "0.12.2"
gdal = { version = "0.5.0", registry = "aspecscire" }

rayon = "1.3.0"
serde_derive = "1.0.104"
serde_cbor = "0.11.1"
serde = "1.0.104"
memmap = "0.7.0"
geo-booleanop = "0.2.0"
