[package]
name = "rasters"
version = "0.1.0"
authors = ["Rajsekar Manokaran <rajsekar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdal = { version = "0.5.0", registry = "aspecscire" }
failure = "0.1.6"
ndarray = "0.13.0"
num = "0.2.1"

cli = { path = "../cli.rs" }
clap = "2.33.0"
cgmath = "0.17.0"
spade = "1.8.1"
geo = "0.12.2"
rayon = "1.3.0"
