on: push
name: Run tests
jobs:
  # The `ci-result` job doesn't actually test anything - it just aggregates the
  # overall build status for bors, otherwise our bors.toml would need an entry
  # for each individual job produced by the job-matrix.
  #
  # Ref: https://github.com/rust-lang/crater/blob/9ab6f9697c901c4a44025cf0a39b73ad5b37d198/.github/workflows/bors.yml#L125-L149
  #
  # ALL THE SUBSEQUENT JOBS NEED THEIR `name` ADDED TO THE `needs` SECTION OF THIS JOB!
  ci-result:
    name: ci result
    runs-on: ubuntu-latest
    needs:
      - test-crate
    steps:
      - name: Mark the job as a success
        if: success()
        run: exit 0
      - name: Mark the job as a failure
        if: "!success()"
        run: exit 1
  test-crate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.63
        gdal:
          - 3.4.1
          - 3.3.2
    name: Test on gdal ${{ matrix.gdal }}, rust ${{ matrix.rust }}
    container:
      image: rmanoka/georust-ci:gdal-${{ matrix.gdal }}-rust-${{ matrix.rust }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Tool versions
        run: gdalinfo --version && rustc --version
      - name: rasters.rs tests
        run: cargo test --all-features
      - name: raster-tools tests
        run: cargo test -p raster-tools
      - name: raster-tools python tests
        run: cd raster-tools && python3 -m tests
